Use `pydantic` > 1
OpenFreeEnergy/alchemiscale pull request #192
Opened 2023-10-12 04:17 UTC by dotsdl

Try un-pinning `pydantic` and allowing it to be pinned by other packages as needed.

2023-11-09 05:46 UTC, dotsdl commented
Looks like we may be getting blocked by `gufe`, which currently requires `openff-models` 0.5.0: https://github.com/openforcefield/alchemiscale/actions/runs/6807892430/job/18511450355?pr=192#step:3:39

I've raised an issue on the `gufe-feedstock` to address: https://github.com/conda-forge/gufe-feedstock/issues/30

2023-11-09 05:53 UTC, dotsdl commented
Otherwise, all tests passing when I run locally. :grin:

2023-12-15 16:24 UTC, dotsdl commented
Getting weird hangs on the test suite in CI, but I can't reproduce the hangs locally. :smiling_face_with_tear:

2024-10-01 16:47 UTC, j-wags commented
If you want to test against upcoming versions of the OpenFF stack with natively pydantic 2 objects, you can grab the OpenFF stack from the `conda-forge/label/openff-interchange_rc` on conda, more details at https://github.com/openforcefield/openff-toolkit/pull/1930/files

2025-01-21 17:08 UTC, dotsdl commented
We can switch wholly to `pydantic` v2 as of `gufe` 1.3, once this PR goes in: https://github.com/OpenFreeEnergy/gufe/issues/397

2025-01-22 15:14 UTC, dotsdl commented
Looks like we got `pydantic` 2 working here!

2025-01-22 18:45 UTC, dotsdl commented
Can I get a review from you @ianmkenney? In particular, can you check that from your perspective we're using proper `pydantic` 2 semantics?

2025-01-23 06:08 UTC, ianmkenney requested changes

2025-01-23 06:08 UTC, ianmkenney commented on alchemiscale/storage/models.py
> +from pydantic import BaseModel, Field, ConfigDict
Field unused?

2025-01-24 05:02 UTC, merged