[WIP] Use `diskcache` for caching `ProtocolDAGResult`s in the Alchemiscale client
OpenFreeEnergy/alchemiscale pull request #271
Opened 2024-04-25 21:46 UTC by ianmkenney

Addresses, in part, #58. Using the [diskcache library](https://grantjenks.com/docs/diskcache/), we can cache `ProtocolDAGResult`s client-side and reduce the number of API calls for calculating free energy differences.

2024-04-30 21:15 UTC, ianmkenney commented
@dotsdl [new error](https://github.com/openforcefield/alchemiscale/actions/runs/8901430808/job/24445248051?pr=271) I haven't seen yet, but doesn't seem to touch anything I changed. Will keep an eye out for it again, but going to assume it's a race condition of some sort for now. 

This should be ready for review now!

2025-02-13 02:51 UTC, dotsdl requested changes
Great work @ianmkenney! Some suggestions, but also one major request: let's perform `zstandard` compression/decompression of `AlchemicalNetwork`s, `Transformation`s, and `ChemicalSystem`s added/retrieved from the disk cache.

2025-02-13 02:51 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +        target_dir = Path().home() / ".other_cache"
```suggestion
        target_dir = Path.home() / ".other_cache"
```

2025-02-13 02:51 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +        assert cache_dir == Path().home() / ".cache" / "alchemiscale"
```suggestion
        assert cache_dir == Path.home() / ".cache" / "alchemiscale"
```

2025-02-13 02:51 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +        user_client._cache.set(str(an_sk), corrupted_bytes)
Brilliant!

2025-02-13 02:51 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +        all_tasks = user_client.get_transformation_tasks(transformation_sk)
```suggestion
        all_tasks = user_client.create_tasks(transformation_sk, count=3)
```

2025-02-13 22:58 UTC, ianmkenney commented on alchemiscale/base/client.py
> +            cache_size_limit=self._cache.size_limit,
https://github.com/grantjenks/python-diskcache/blob/ebfa37cd99d7ef716ec452ad8af4b4276a8e2233/diskcache/core.py#L2373

Attributes are set dynamically with the reset call to particular settings attribute.

2025-02-13 23:38 UTC, ianmkenney commented on alchemiscale/interface/client.py
> +            cached_keyed_chain = self._cache.get(str(scopedkey), None).decode("utf-8")
Should be simple to add this in.

2025-02-14 20:36 UTC, ianmkenney commented on alchemiscale/interface/client.py
> +            keyedchain_json = json.dumps(content, cls=JSON_HANDLER.encoder)
I'd like to avoid mixed return types if possible. Since going from a keyed chain to a string is fairly cheap, I don't see an immediate need to add that behavior.

2025-02-15 00:46 UTC, dotsdl commented on alchemiscale/base/client.py
> +            cache_size_limit=self._cache.size_limit,
Ah cool, thanks for the clarification!

2025-02-15 01:00 UTC, dotsdl approved these changes
Brilliant work @ianmkenney! This is an elegant approach to adding persistent caching client-side!

2025-02-15 01:00 UTC, dotsdl commented on alchemiscale/compression.py
> +    return compress_keyed_chain_zstd(keyed_chain)
Brilliant!

2025-02-15 01:00 UTC, dotsdl commented on alchemiscale/compression.py
> +    gufe_object = GufeTokenizable.from_keyed_chain(keyed_chain)
This is so nice!

2025-02-15 01:16 UTC, merged