Implement task restart policies
OpenFreeEnergy/alchemiscale pull request #280
Opened 2024-07-16 15:25 UTC by ianmkenney

closes #277

2024-09-19 22:04 UTC, pep8speaks commented
Hello @ianmkenney! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`alchemiscale/storage/models.py`](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py):

> [Line 153:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L153): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 157:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L157): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 165:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L165): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 174:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L174): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 208:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L208): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 216:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L216): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 217:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/models.py#L217): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

* In the file [`alchemiscale/storage/statestore.py`](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py):

> [Line 1432:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1432): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 1435:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1435): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 79 characters)
> [Line 1450:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1450): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 1627:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1627): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 1628:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1628): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 79 characters)
> [Line 1634:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1634): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 1641:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L1641): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 2448:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2448): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 2464:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2464): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 2816:5](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2816): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 2822:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2822): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 2838:9](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2838): [E266](https://duckduckgo.com/?q=pep8%20E266) too many leading '#' for block comment
> [Line 2849:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2849): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 2875:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2875): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 2877:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2877): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 2902:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2902): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 2908:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2908): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 2912:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2912): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 2917:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2917): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 2928:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2928): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 2940:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2940): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 2947:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2947): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 79 characters)
> [Line 2969:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2969): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 2972:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2972): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 2976:80](https://github.com/OpenFreeEnergy/alchemiscale/blob/cf0e9615f722c785e9e7e8f955adeb0eeb77045e/alchemiscale/storage/statestore.py#L2976): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (145 > 79 characters)
> [Line 2979:80](https [...]

2025-01-20 04:39 UTC, dotsdl requested changes
Thanks for this impressive feature @ianmkenney! I have a few notes, and I've made some modifications where it was obvious to me what to do.

Can you address the notes and fix any broken tests? After that, I think we should be good to merge!

2025-01-20 04:39 UTC, dotsdl commented on alchemiscale/tests/integration/storage/test_statestore.py
> +            raise NotImplementedError
Ah, I see we check this behavior in `test_action_task`.

2025-01-20 04:39 UTC, dotsdl commented on alchemiscale/tests/integration/storage/test_statestore.py
> +            raise NotImplementedError
Ah, I see we check this behavior in `test_cancel_task`.

2025-01-21 22:13 UTC, ianmkenney commented on alchemiscale/storage/statestore.py
> +        query_safe_task_list = [str(task) for task in tasks if task]
If a `None` were passed in this would filter it out. This was made more explicit in the current branch with a sync with main (https://github.com/OpenFreeEnergy/alchemiscale/pull/280/commits/d331cc45ee9462b304e817e10d2d0bd3e05e9383).

2025-01-21 22:49 UTC, ianmkenney commented on alchemiscale/storage/models.py
> +        return self.pattern == other.pattern
Well it appears I never ended up using it. I'll remove this and we can revisit the question if we ever implement `__eq__` in the future.

2025-01-21 23:08 UTC, ianmkenney commented on alchemiscale/storage/statestore.py
> +    # TODO: validation of taskhubs variable, will fail in weird ways if not enforced
I think this might have been more of a passing thought when writing. This was introduced in (https://github.com/OpenFreeEnergy/alchemiscale/pull/280/commits/7acc0036039324c86d2348908d990c8e121775f8) and I can't find anything in there that is alarming. From what I can see this isn't much of an issue. Our current usage with the interface api does scope validation and the taskhub scoped keys fed in come from the `n4js.get_taskhubs`. I've lost the full context of the comment and it might even be irrelevant now.

2025-01-21 23:10 UTC, ianmkenney commented on alchemiscale/storage/statestore.py
> +        transform_results = defaultdict(None)
You're right, will change it to a standard dict.

2025-01-21 23:49 UTC, ianmkenney commented on alchemiscale/tests/integration/storage/test_statestore.py
> +        ).records[0]["applies_count"]
Good catch, thanks!

2025-01-23 04:17 UTC, merged